### ISSUE TITLE
SendCodeRequest Method Failed

### ISSUE THREAD

**Issue by cybergogic** [sochix/TLSharp#17]
Hi, Ilya. Thank you for the great work.
AuthUser test has failed because SendCodeRequest method thrown a exception in mscorlib.dll and i can't receive SMS code to my phone number. I try 0,1 and 5 value in sms_type parameter.

TestConnection and AutheficationWorks works fine.

Visual Studio 2015 Community, Win7 32-bit

Regards, Egor

**Comment by sochix** [comment]
Hi! Did you provide your phone_numbers in app.config file? Please post a stack trace

**Comment by cybergogic** [comment]
yes, i filled up the app.config because without it any test will be failed.

Test has crashed in these string: 
await _sender.Send(request);
Exception thrown: 'System.NullReferenceException' in TLSharp.Core.dll
Exception thrown: 'System.NullReferenceException' in mscorlib.dll

i try now in 64-bit Win2012 R2 Server. i think, that it's 32-bit compatibility troubles with VS2015 and async calls.

**Comment by POSBean** [comment]
Hi sir,

This Source is not working in VS 2012

**Comment by cybergogic** [comment]
Had a same error in 64-bit platform

stack trace below

Test Name:	AuthUser
Test FullName:	TLSharp.Tests.NotificatioClientTests.AuthUser
Test Source:	E:\Current\ICQ_Jabber\Telegram\docs\TLSharp-master\TLSharp.Tests\NotificatioClientTests.cs : line 46
Test Outcome:	Failed
Test Duration:	0:00:00,2830459

Result StackTrace:	
at TLSharp.Core.TelegramClient.<SendCodeRequest>d__10.MoveNext() in E:\Current\ICQ_Jabber\Telegram\docs\TLSharp-master\TLSharp.Core\TelegramClient.cs:line 73
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at TLSharp.Tests.NotificatioClientTests.<AuthUser>d__13.MoveNext() in E:\Current\ICQ_Jabber\Telegram\docs\TLSharp-master\TLSharp.Tests\NotificatioClientTests.cs:line 52
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
Result Message:	
Test method TLSharp.Tests.NotificatioClientTests.AuthUser threw exception: 
System.NullReferenceException: Object reference not set to an instance of an object.

**Comment by sochix** [comment]
@POSBean yes, it won't work in VS2012.

**Comment by cybergogic** [comment]
have any ideas?

**Comment by sochix** [comment]
@cybergogic set a breakpoint at TelegramClient line 73. And go into Send method by F11. I need some context of exception.

**Comment by nezam1** [comment]
hello please install vs 2015 and run it

**Comment by rashcms** [comment]
same problem

**Comment by DanialNazari** [comment]
hi Ilya, i have same problem and i can't get verification code from telegram ,
i think if you explain more about 'Sending messages set-up' step everything will be better ...

more detail about my problem when i run test : 	
Test method TLSharp.Tests.NotificatioClientTests.AuthUser threw exception: 
System.IO.EndOfStreamException: Unable to read beyond the end of the stream.

of course i do everything in 'Sending messages set-up' step .

please give me way to fix it ...
thanks ...

**Comment by sochix** [comment]
@DanialNazari see Readme.md

**Comment by DanialNazari** [comment]
@sochix hi , i see that very well (in details) before i posted here, an i do anything in readme.md ,but  
 'Sending messages set-up' step is ambiguous for me , if you can explain more this step (in Technically aspects) 
thanks for your attention ...

**Comment by sochix** [comment]
@DanialNazari sorry, not get what you mean

**Comment by DanialNazari** [comment]
hi again, 
![untitled1](https://cloud.githubusercontent.com/assets/15088929/10664040/ce324f7c-7874-11e5-8708-9593fc36a2f7.png)
in this method (decodeMessage) ,when i got the first response, the length of body is 4 , and in line 108  ReadUint64 want to read 8 byte from inputreader , and inputreader does not have 8 byte...
in this line (108 ) i got exception below( as i said before) : 
System.IO.EndOfStreamException: Unable to read beyond the end of the stream.

what wrong ? what can i do?

**Comment by delphiassistant** [comment]
System.IO.EndOfStreamException usually comes from wrong server address. Not all the telegram servers listed in read.me file work fine. Change server address to different addresses in TcpTransport.cs and see which one works.

**Comment by mehdir92** [comment]
@delphiassistant  i change  all server addresses but Still has problem :(

**Comment by cybergogic** [comment]
i re-download the package and now i have a same EndOfStreamException with same ip and hash settings. in previous version, which i downloaded in Oct, 7, these piece of code works fine =(
waiting for any fixes...

**Comment by cybergogic** [comment]
sorry, previous version have same bug too (4 bytes instead of 8) maybe telegram has change in protocol

**Comment by hamidpp** [comment]
to correct you should change your ip server address.

**Comment by cybergogic** [comment]
@hamidpp
what server ip you use? i tried all of recomended...

**Comment by hamidpp** [comment]
when the run project the session.dat file will be create in bin folder, you first delete this file and clean solution then test again with this ip servers :
Server 1: 149.154.175.50:443    (recommended)
Server 2: 149.154.167.51:443
Server 3: 149.154.175.100:443
Server 4: 149.154.167.91:443
Server 5: 91.108.56.165:443

**Comment by cybergogic** [comment]
@hamidpp 
great! problem has solved with manual deleting file session dat.
thank you!

**Comment by DanialNazari** [comment]
@hamidpp hi hamid , your post helped me to receive telegram code but i still receive  EndOfStreamException when debug authUser() method (i do not use ip server that you recomend because  checkPhone() method failed with various error ; MIGRATE , ...)
what's wrong ?

**Comment by hamidpp** [comment]
i get this error in some times,but this fixed with delete session.dat file and clean solution.if you get PHONE_MIGRATE_X or NETWORK_MIGRATE_X 
see this address to help : https://core.telegram.org/method/auth.sendCode
you should repeat the query to data-center X. i suggest create array of data center e.g
public static List<DcOptionConstructor> dcList = new List<DcOptionConstructor> {
                new DcOptionConstructor() {id = 1, hostname = "", ip_address = "149.154.175.50", port = 443 },
                new DcOptionConstructor() {id = 2, hostname = "", ip_address = "149.154.167.51", port = 443 },
                new DcOptionConstructor() {id = 3, hostname = "", ip_address = "149.154.175.100", port = 443 },
               new DcOptionConstructor() {id = 4, hostname = "", ip_address = "149.154.167.91", port = 443 },
                new DcOptionConstructor() {id = 5, hostname = "", ip_address = "91.108.56.165", port = 443 }

and use the id number corresponding to X example PHONE_MIGRATE_4 => ( id 4 = 149.154.167.91)

        }

**Comment by cybergogic** [comment]
@DanialNazari , @hamidpp  i still have a same problem. if Telegram is running in my phone, i receive code via Telegram, paste this in debug and AuthTest works fine. if Telegram isn't running in my phone, or phone number is not registered, i receive the Telegram code in sms (twice from different sources: first sms immediately, second sms with 1-2 minutes delay) and i have EndOfSteramException in MakeAuth method, and the test has breaked. Also i have FileNotFound Exception in mscorlib.dll with client.connect() method, but these exception do not crash the test.

somebody help

**Comment by NetherX** [comment]
@cybergogic Hey , Download The Latest Version Of This Package , MarkerMetro.Unity.Ionic.Zlib.

**Comment by cybergogic** [comment]
@NetherX using version 2.0.0.14 it's wrong?

**Comment by novinp** [comment]
hi
i have read all of the conversiones in this Issues and other Issueses
i have "cybergogic" problem.

1-change server provided ips
2-delete session

i can get code,activate and send message when telegram is actived on my phone 
but! if telegram not activated on my phone , i can recive the telegram activation code on my phone but application has been stoped by the below error:
processMessage(result.Item2, result.Item3, messageReader, request);

case 0xf35c6d01: // rpc_result
								 //logger.debug("MSG rpc_result");
					return HandleRpcResult(messageId, sequence, messageReader, request);

return HandleRpcResult(messageId, sequence, messageReader, request);

on HandleRpcResult

on public override void OnResponse(BinaryReader reader)
_phoneRegistered=true
_phoneCodeHash=33440dc5fbb3eccb46

throw exception on this line 
Unable to read beyond the end of the stream.
var sendCodeTimeout = reader.ReadInt32();
var isPassword = reader.ReadUInt32() == boolTrue;

**Comment by Boroumandan** [comment]
Hello there
I have problem same as Previous message
I get error in this line
var sendCodeTimeout = reader.ReadInt32();

Please Help
Thanks

**Comment by dinhducit** [comment]
I got same issue, please help me to solve it :)

**Comment by dinhducit** [comment]
i still have a same problem. if Telegram is running in my phone, i receive code via Telegram, paste this in debug and AuthTest works fine. if Telegram isn't running in my phone, or phone number is not registered, i receive the Telegram code in sms (twice from different sources: first sms immediately, second sms with 1-2 minutes delay) and i have EndOfSteramException in MakeAuth method, and the test has breaked. Also i have FileNotFound Exception in mscorlib.dll with client.connect() method, but these exception do not crash the test.

somebody help

**Comment by dinhducit** [comment]
Can someone help me?

**Comment by paulo-apoloni** [comment]
Same problem here
Sometimes i get "System.IO.EndOfStreamException: Unable to read beyond the end of the stream." and sometimes "store_invalid_object_type"

**Comment by hamidpp** [comment]
change your server ip address to solve.

**Comment by knocte** [comment]
@hamidpp how to change the IP address?

**Comment by LukZucca** [comment]
@knocte 
Have you solved the problem? If yes, please can you explain how?
Thank you in advance.

**Comment by AbbasKhalili** [comment]
I have same problem. finally I know that for every request should call  ConnectAsync();  method.
