### ISSUE TITLE
Constructor Invalid Or Context.Init Not Called !

### ISSUE THREAD

**Issue by hosseinGanjyar** [sochix/TLSharp#768]
I updated library and have a error in connect and work with telegram.

>**error**: Constructor Invalid Or Context.Init Not Called !

> **version: TLSharp 0.1.0.371**

**Comment by VladSnap** [comment]
I also have this error. Occurs only after the application is restarted and the session is read from the file.
Old versions of the library also do not work, I tried different

reproduction
run app > connection > auth code > send any request (many) > success > close app (session saved to file)
run app > fileSessionStore.Load(...) > exception:

>InvalidDataException: Constructor Invalid Or Context.Init Not Called !
>  NullReferenceException:
>    at TeleSharp.TL.TLContext.getType(Int32 Constructor)
>    at TeleSharp.TL.ObjectUtils.DeserializeObject(BinaryReader reader)

**Comment by VladSnap** [comment]
I found the reason. As a temporary solution to the problem, you need to add a call to TLContext.Init () when you start your application.
I will prepare a PullRequest to fix this problem.

**Comment by knocte** [comment]
Fixed by https://github.com/sochix/TLSharp/commit/47e973823a0c0695cde4c70e0ab3da27b611d280

**Comment by hosseinGanjyar** [comment]
heyyyyyyyyyyyy...... @knocte wait!
My problem not solved yet.
@VladSnap Where should i call TLContext.Init?

**Comment by VladSnap** [comment]
In the latest version of the library, this error should not exist.
In my case it helped, maybe you have an error for other reasons, try to use debugging and find it.

**Comment by hosseinGanjyar** [comment]
```
  try
            {
                var session = new FileSessionStore();
                TelegramClient client = new TelegramClient(apiId, apiHash, session , "session");
            }
catch (Exception exc)
            {
               //  Constructor Invalid Or Context.Init Not Called !
            }
```

**Comment by VladSnap** [comment]
Show all stacktrace exception.

**Comment by vmato** [comment]
Problem persist in nuget package

Stack trace:

   в TeleSharp.TL.ObjectUtils.DeserializeObject(BinaryReader reader)
   в TLSharp.Core.Session.FromBytes(Byte[] buffer, ISessionStore store, String sessionUserId)
   в TLSharp.Core.FileSessionStore.Load(String sessionUserId)
   в TLSharp.Core.Session.TryLoadOrCreateNew(ISessionStore store, String sessionUserId)
   в TLSharp.Core.TelegramClient..ctor(Int32 apiId, String apiHash, ISessionStore store, String sessionUserId, TcpClientConnectionHandler handler)
   
Inner exception stack trace:

   в System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   в TeleSharp.TL.TLContext.getType(Int32 Constructor)
   в TeleSharp.TL.ObjectUtils.DeserializeObject(BinaryReader reader)

**Comment by knocte** [comment]
@vmato don't post just your stacktraces manually, paste the entire text resulting from `ex.ToString()` please (ToString automatically outputs the name of the exception, the message, the stacktrace and the stacktraces of all inner exceptions).

**Comment by vmato** [comment]
Ok. Here it is:
```

System.IO.InvalidDataException: Constructor Invalid Or Context.Init Not Called ! ---> System.Collections.Generic.KeyNotFoundException: Данный ключ отсутствует в словаре.
   в System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   в TeleSharp.TL.TLContext.getType(Int32 Constructor)
   в TeleSharp.TL.ObjectUtils.DeserializeObject(BinaryReader reader)
   --- Конец трассировки внутреннего стека исключений ---
   в TeleSharp.TL.ObjectUtils.DeserializeObject(BinaryReader reader)
   в TLSharp.Core.Session.FromBytes(Byte[] buffer, ISessionStore store, String sessionUserId)
   в TLSharp.Core.FileSessionStore.Load(String sessionUserId)
   в TLSharp.Core.Session.TryLoadOrCreateNew(ISessionStore store, String sessionUserId)
   в TLSharp.Core.TelegramClient..ctor(Int32 apiId, String apiHash, ISessionStore store, String sessionUserId, TcpClientConnectionHandler handler)
   в Tg.Program..ctor() в C:\source\Tg\Program.cs:строка 62
   в Tg.Program.Instance() в C:\source\Tg\Program.cs:строка 51
   в Tg.Program.Main(String[] args) в C:\source\Tg\Program.cs:строка 1097


```

**Comment by knocte** [comment]
Can you switch your locale to English to have an English exception message please?
